import streamlit as st
import datetime 
import requests 
import sys 

BASE_URL = "http://localhost:8000" #Backedn endpoint


st.set_page_config(
    page_title =  "🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state = "expanded",
)

st.title("🌍 Travel Planner Agentic Application ")

#Display chat history 
st.header("I can help you plan a trip from first day to the last. Let me know where do you want to visit ?")

# Initialize chat history 
if "messages" not in st.session_state:
    st.session_state.messages = []

with st.form(key = "query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder = "e.g Plan a trip to Marrakech for 5 days.")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        #Show user message
        with st.spinner("Agent is thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)
        
        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""#🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime("%Y-%m-%d at %H:%M")}
            # **Created by:** Hamza's travel agent

            ---
            {answer}
            ---

            *This plan was generated by AI. AI can make mistakes. Please verify prices and dates.
            """
            st.markdown(markdown_content)
        else :
            st.error("Agent failed to respond:" + response.text)
        
    except Exception as e:
        raise f"The response failed due to {e}"


            



